services:
  local-geocoder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:5636'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=5636
      - HOST=0.0.0.0
      - NODE_OPTIONS=--max-old-space-size=4096
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://0.0.0.0:5636/healthcheck']
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    volumes:
      - geonames_data:/app/geonames_dump
    networks:
      - geocoder-network

volumes:
  geonames_data:
    name: geocoder_geonames_data

networks:
  geocoder-network:
    name: geocoder-network
    driver: bridge
