// Country code mappings
exports.countryMappings = {
  'united states': 'US',
  usa: 'US',
  'united kingdom': 'GB',
  uk: 'GB',
  england: 'GB',
  britain: 'GB',
  'great britain': 'GB',
  greece: 'GR',
  france: 'FR',
  germany: 'DE',
  spain: 'ES',
  italy: 'IT',
  japan: 'JP',
  china: 'CN',
  india: 'IN',
  canada: 'CA',
  australia: 'AU',
  ireland: 'IE',
  portugal: 'PT',
  netherlands: 'NL',
  belgium: 'BE',
  sweden: 'SE',
  norway: 'NO',
  denmark: 'DK',
  finland: 'FI',
  austria: 'AT',
  switzerland: 'CH',
  poland: 'PL',
  russia: 'RU',
  ukraine: 'UA',
  turkey: 'TR',
  mexico: 'MX',
  brazil: 'BR',
  argentina: 'AR',
  chile: 'CL',
  colombia: 'CO',
  peru: 'PE',
  venezuela: 'VE',
  iceland: 'IS',
  romania: 'RO',
  bulgaria: 'BG',
  hungary: 'HU',
  czechia: 'CZ',
  'czech republic': 'CZ',
  slovakia: 'SK',
  slovenia: 'SI',
  croatia: 'HR',
  serbia: 'RS',
  latvia: 'LV',
  lithuania: 'LT',
  estonia: 'EE',
  luxembourg: 'LU',
  malta: 'MT',
  cyprus: 'CY',
  'new zealand': 'NZ',
  singapore: 'SG',
  malaysia: 'MY',
  indonesia: 'ID',
  thailand: 'TH',
  vietnam: 'VN',
  philippines: 'PH',
  'south korea': 'KR',
  korea: 'KR',
  'north korea': 'KP',
  mongolia: 'MN',
  kazakhstan: 'KZ',
  // Add more as needed
};

// US State code mappings
exports.stateMappings = {
  alabama: 'AL',
  alaska: 'AK',
  arizona: 'AZ',
  arkansas: 'AR',
  california: 'CA',
  colorado: 'CO',
  connecticut: 'CT',
  delaware: 'DE',
  florida: 'FL',
  georgia: 'GA',
  hawaii: 'HI',
  idaho: 'ID',
  illinois: 'IL',
  indiana: 'IN',
  iowa: 'IA',
  kansas: 'KS',
  kentucky: 'KY',
  louisiana: 'LA',
  maine: 'ME',
  maryland: 'MD',
  massachusetts: 'MA',
  michigan: 'MI',
  minnesota: 'MN',
  mississippi: 'MS',
  missouri: 'MO',
  montana: 'MT',
  nebraska: 'NE',
  nevada: 'NV',
  'new hampshire': 'NH',
  'new jersey': 'NJ',
  'new mexico': 'NM',
  'new york': 'NY',
  'north carolina': 'NC',
  'north dakota': 'ND',
  ohio: 'OH',
  oklahoma: 'OK',
  oregon: 'OR',
  pennsylvania: 'PA',
  'rhode island': 'RI',
  'south carolina': 'SC',
  'south dakota': 'SD',
  tennessee: 'TN',
  texas: 'TX',
  utah: 'UT',
  vermont: 'VT',
  virginia: 'VA',
  washington: 'WA',
  'west virginia': 'WV',
  wisconsin: 'WI',
  wyoming: 'WY',
};
